### PR TITLE
update uri to use https

### PR DESCRIPTION
**Pull request by stephenjamieson**
AirNow requires HTTPS as of Feb 3rd 2023

### CODE REVIEW

**Comment by asymworks** [comment]
Thanks for your contribution @stephenjamieson.  CI checks are failing because of outdated dependencies.  I have updated them in the master branch - can you please re-baseline against the current master branch so GitHub picks up the new versions?  That should let CI pass.

**Comment by stephenjamieson** [comment]
Thank you @asymworks, I merged the changes but reviewing the CI logs it looks like they're failing due to the api key used being invalid

**Comment by asymworks** [comment]
I think the tests might be failing because they are still set up to expect `http` instead of `https` when they generate the simulated responses.  Try changing the regex at https://github.com/asymworks/pyairnow/blob/master/tests/conftest.py#L18 to accept the `https` and see if the tests pass.

**Comment by stephenjamieson** [comment]
Thanks @asymworks, I had searched for the address but didn't think to search with escapes in regexes

**Comment by asymworks** [comment]
Thanks, looks good to me!

**Pull request merged**
